/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VideoDetailsService } from "../videoDetails.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VideoDetailsCreateInput } from "./VideoDetailsCreateInput";
import { VideoDetails } from "./VideoDetails";
import { VideoDetailsFindManyArgs } from "./VideoDetailsFindManyArgs";
import { VideoDetailsWhereUniqueInput } from "./VideoDetailsWhereUniqueInput";
import { VideoDetailsUpdateInput } from "./VideoDetailsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VideoDetailsControllerBase {
  constructor(
    protected readonly service: VideoDetailsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VideoDetails })
  @nestAccessControl.UseRoles({
    resource: "VideoDetails",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVideoDetails(
    @common.Body() data: VideoDetailsCreateInput
  ): Promise<VideoDetails> {
    return await this.service.createVideoDetails({
      data: {
        ...data,

        video: data.video
          ? {
              connect: data.video,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        duration: true,
        id: true,
        language: true,
        tags: true,
        updatedAt: true,

        video: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [VideoDetails] })
  @ApiNestedQuery(VideoDetailsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "VideoDetails",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async videoDetailsItems(
    @common.Req() request: Request
  ): Promise<VideoDetails[]> {
    const args = plainToClass(VideoDetailsFindManyArgs, request.query);
    return this.service.videoDetailsItems({
      ...args,
      select: {
        createdAt: true,
        duration: true,
        id: true,
        language: true,
        tags: true,
        updatedAt: true,

        video: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VideoDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VideoDetails",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async videoDetails(
    @common.Param() params: VideoDetailsWhereUniqueInput
  ): Promise<VideoDetails | null> {
    const result = await this.service.videoDetails({
      where: params,
      select: {
        createdAt: true,
        duration: true,
        id: true,
        language: true,
        tags: true,
        updatedAt: true,

        video: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VideoDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VideoDetails",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVideoDetails(
    @common.Param() params: VideoDetailsWhereUniqueInput,
    @common.Body() data: VideoDetailsUpdateInput
  ): Promise<VideoDetails | null> {
    try {
      return await this.service.updateVideoDetails({
        where: params,
        data: {
          ...data,

          video: data.video
            ? {
                connect: data.video,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          duration: true,
          id: true,
          language: true,
          tags: true,
          updatedAt: true,

          video: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VideoDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VideoDetails",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVideoDetails(
    @common.Param() params: VideoDetailsWhereUniqueInput
  ): Promise<VideoDetails | null> {
    try {
      return await this.service.deleteVideoDetails({
        where: params,
        select: {
          createdAt: true,
          duration: true,
          id: true,
          language: true,
          tags: true,
          updatedAt: true,

          video: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
