/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ExcelFile } from "./ExcelFile";
import { ExcelFileCountArgs } from "./ExcelFileCountArgs";
import { ExcelFileFindManyArgs } from "./ExcelFileFindManyArgs";
import { ExcelFileFindUniqueArgs } from "./ExcelFileFindUniqueArgs";
import { CreateExcelFileArgs } from "./CreateExcelFileArgs";
import { UpdateExcelFileArgs } from "./UpdateExcelFileArgs";
import { DeleteExcelFileArgs } from "./DeleteExcelFileArgs";
import { ExcelFileService } from "../excelFile.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ExcelFile)
export class ExcelFileResolverBase {
  constructor(
    protected readonly service: ExcelFileService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ExcelFile",
    action: "read",
    possession: "any",
  })
  async _excelFilesMeta(
    @graphql.Args() args: ExcelFileCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ExcelFile])
  @nestAccessControl.UseRoles({
    resource: "ExcelFile",
    action: "read",
    possession: "any",
  })
  async excelFiles(
    @graphql.Args() args: ExcelFileFindManyArgs
  ): Promise<ExcelFile[]> {
    return this.service.excelFiles(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ExcelFile, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ExcelFile",
    action: "read",
    possession: "own",
  })
  async excelFile(
    @graphql.Args() args: ExcelFileFindUniqueArgs
  ): Promise<ExcelFile | null> {
    const result = await this.service.excelFile(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ExcelFile)
  @nestAccessControl.UseRoles({
    resource: "ExcelFile",
    action: "create",
    possession: "any",
  })
  async createExcelFile(
    @graphql.Args() args: CreateExcelFileArgs
  ): Promise<ExcelFile> {
    return await this.service.createExcelFile({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ExcelFile)
  @nestAccessControl.UseRoles({
    resource: "ExcelFile",
    action: "update",
    possession: "any",
  })
  async updateExcelFile(
    @graphql.Args() args: UpdateExcelFileArgs
  ): Promise<ExcelFile | null> {
    try {
      return await this.service.updateExcelFile({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ExcelFile)
  @nestAccessControl.UseRoles({
    resource: "ExcelFile",
    action: "delete",
    possession: "any",
  })
  async deleteExcelFile(
    @graphql.Args() args: DeleteExcelFileArgs
  ): Promise<ExcelFile | null> {
    try {
      return await this.service.deleteExcelFile(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
